name: Milestone Planning

on:
  # Trigger on milestone events
  milestone:
    types: [created, edited, deleted]
  # Trigger on issue events
  issues:
    types: [opened, edited, deleted, transferred, milestoned, demilestoned, labeled, unlabeled]

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Milestone Planning
        uses: elliotxx/auto-milestone-summary-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planning_label: planning
          categories: |
            [
              "area/ai",
              "area/search",
              "area/insight",
              "area/cluster-mgmt",
              "area/experience",
              "area/installation",
              "area/performance",
              "area/server",
              "area/storage",
              "area/syncer",
              "bug",
              "enhancement",
              "documentation"
            ]
